""" Chock Full O' Consts (funny, stays in) """
DEBUG = 1
# MIDI msg components
MIDI_NOTE_TYPE = 0
MIDI_CC_TYPE = 1
MIDI_PB_TYPE = 2
MIDI_MSG_TYPES = (MIDI_NOTE_TYPE,
 MIDI_CC_TYPE,
 MIDI_PB_TYPE)
MIDI_NOTE_ON_STATUS = 144
MIDI_NOTE_OFF_STATUS = 128
MIDI_CC_STATUS = 176
MIDI_PB_STATUS = 224

# MIDI note numbers for the transport controls
TRANSPORT_CHANNEL = 7   # 0-indexed 0-15
TRANSPORT_PLAY = 4 # restart, since it restarts
TRANSPORT_STOP = 0 # play, since we are using restart
TRANSPORT_RECORD = 1 # record
TRANSPORT_TAP_TEMPO = 3 # note repeat / tap tempo
TRANSPORT_SEEK_FFWD = 6 # next or right arrow
TRANSPORT_SEEK_RWD = 5 # prev or left arrow
TRANSPORT_BACK_TO_ARRANGER = 2 # erase
TRANSPORT_TEMPO = 25

# MIDI note numbers for the session navigation
SESSION_NAVIGATE_UP = 16
SESSION_NAVIGATE_DOWN = 17
SESSION_NAVIGATE_LEFT = 18
SESSION_NAVIGATE_RIGHT = 19
SESSION_SCENE_PREVIOUS = 20
SESSION_SCENE_NEXT = 21
SESSION_SCENE_LAUNCH = 8

#MIDI cc's for mixer
MIXER_CHANNEL = 7   # 0-indexed 0-15
MASTER_VOLUME = 9
MASTER_PAN = 10
MASTER_BOOTH = 11



MASCHINE_DEVICE_PORT_NAME = 'Maschine Controller'

STATUS_MASK = 240
CHAN_MASK = 15
NOTEON_STATUS = 144
NOTEOFF_STATUS = 128
NOTEON_STATUS_CH8 = 151
NOTEOFF_STATUS_CH8 = 135
CC_STATUS = 176
CC_STATUS_CH7 = 182
CC_STATUS_CH8 = 183
NOTE_OFF_STATUS = 128
NOTE_ON_STATUS = 144
CLIP_TRIGGER_CHANNEL = 0
GENERAL_REQUEST_CHANNEL = 4
MAX_TRACKS = 16
MAX_SCENES = 16
PAD_SIZE = 4
PAD_NOTES = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
NAVIGATION_OFFSET_DEFAULT = 1
NAVIGATION_OFFSET1 = 4
NAVIGATE_OFFSET1_NOTE = 21
MASCHINE_MODE_SCENE = 21 #was 100
MASCHINE_MODE_PATTERN = 101
MASCHINE_MODE_MUTE = 102
MASCHINE_MODIFIER = (MASCHINE_MODE_SCENE,
 MASCHINE_MODE_PATTERN,
 MASCHINE_MODE_MUTE)
MASCHINE_DISPLAY_BPM = 127

CLIP_TRIGGER_CHANNEL = 0
TRACK_MIXER_CHANNEL = 6
SONG_TRIGGER_CHANNEL = 7
SCENE_OFFSET1 = 90
SCENE_OFFSET2 = 91
SCENE_OFFSET3 = 92
SCENE_OFFSET4 = 93
SCENE_MODE_TRIGGERED = 1
SCENE_MODE_INACTIVE = -1
SCENE_MODE_ACTIVE = 0
SYSEX_SCREEN_BEGIN_LINE_1 = (240, 0, 0, 102, 20, 18, 0)
SYSEX_SCREEN_BEGIN_LINE_2 = (240, 0, 0, 102, 21, 18, 56)
SYSEX_SCREEN_BUFFER_15 = '               '
SYSEX_SCREEN_BUFFER_30 = '                              '
SYSEX_SCREEN_END = (247,)
WELCOME_SYSEX_MESSAGE = (240, 0, 72, 69, 76, 76, 79, 247)
BUILD_MAP_SYSEX_MESSAGE = (240, 0, 66, 85, 73, 76, 68, 247)
GOODBYE_SYSEX_MESSAGE = (240, 0, 66, 89, 69, 247)
SYSEX_BEGIN = (240, 0)
SYSEX_END = (247, 0)

#+++ okay decompyling
# decompiled 1 files: 1 okay, 0 failed, 0 verify failed
